### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by gldn** [Dahlgren/docker-banana-split#2]
After FFMPEG black screen search completes, the thumbnails are not showing (broken images). This behavior exists on Chrome (Mac and Windows) and Firefox (Mac).

I think the issue is that the link generates the time code as NaN in the link:
http://server:port/video.php?function=thumbnail&time=**NaN**&f=filename.mp4

If I manually change NaN to 720 (eg, to see a thumbnail at 12 minutes in), I am able to see thumbnails easily.

**Comment by Dahlgren** [comment]
Relevant code at https://github.com/pathartl/banana-split/blob/d1df3e9aeb2a2240d15dcd780abb23ccd596086e/js/controllers.js#L73

**Comment by Dahlgren** [comment]
Not sure if related to the ffmpeg config set by the package or something in the banana split code. Haven't used the application for quite a while.

**Comment by gldn** [comment]
Appreciate the work on Dockerizing this (and hopefully you got the Reddit gold I sent you yesterday). It's definitely good enough for my uses without the thumbnails.

I am basically code illiterate, but I wonder if the issue is that seconds are being reported with decimals (e.g. 719.75 instead of 720).  I can manually pull thumbnails using whole numbers, but not decimals.  I'll take the issue to the banana-split repo if I want to spend more time on this :)
